project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "Computational Statistics"
  description: |
    Resources page for the Computational Statistics course
  site-url: "https://math-ku.github.io/compstat/"
  repo-url: "https://github.com/math-ku/compstat"
  repo-actions: [edit, issue]
  search: true

  navbar:
    search: true
    title: CompStat
    left:
      - text: "Home"
        href: index.qmd
      - assignments.qmd

format:
  html:
    toc: true
    theme: cosmo
    html-math-method: katex
  beamer:
    incremental: true
    aspectratio: 1610
    classoption: onlytextwidth
    theme: moloch
    colortheme: moloch-tomorrow
    fig-width: 2.6
    fig-height: 2
    colorlinks: true
    linkcolor: black
    urlcolor: DodgerBlue3
    highlight-style: tango
    cite-method: biblatex
    indent: true
    template-partials:
      - slides/tightlist.tex
    include-in-header:
      - text: |
          \setbeamertemplate{page number in head/foot}[appendixframenumber]
          \setbeameroption{show notes}
          \usepackage{fontsetup}
      - file: slides/packages.tex

date-format: long

execute:
  freeze: auto

bibliography: assets/bibliography.bib
