project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Computational Statistics"

format:
  html:
    toc: true
    html-math-method: katex

date-format: long

execute:
  freeze: auto

bibliography: assets/bibliography.bib
