format:
  beamer:
    incremental: false
    classoption:
      - handout
    include-in-header:
      - text: |
          \renewcommand{\pdfpcnote}[1]{}

filters:
  - incremental-to-static-slides

execute:
  cache: false
