format:
  beamer:
    incremental: false
    include-in-header:
      - text: |
          \setbeamertemplate{page number in head/foot}[appendixframenumber]
          \usepackage{fontsetup}

execute:
  cache: false

filters:
  - incremental-to-static-slides
