project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "Computational Statistics"
  description: |
    Resources page for the Computational Statistics course
  site-url: "https://math-ku.github.io/compstat/"
  repo-url: "https://github.com/math-ku/compstat"
  repo-actions: [edit, issue]
  search: true

format:
  html:
    toc: true
    theme: cosmo
    html-math-method: katex

date-format: long

execute:
  freeze: auto

bibliography: assets/bibliography.bib
