project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "Computational Statistics"
  description: |
    Resources page for the Computational Statistics course

format:
  html:
    toc: true
    html-math-method: katex

date-format: long

execute:
  freeze: auto

bibliography: assets/bibliography.bib
