defaultIndent: "  "
specialBeginEnd:
  leftRightParen:
    begin: '\\left\('
    end: '\\right\)'
    lookForThis: 1
  leftRightSquare:
    begin: '\\left\['
    end: '\\right\]'
    lookForThis: 1
  leftRightCurly:
    begin: '\\left\\{'
    end: '\\right\\}'
    lookForThis: 1
modifyLineBreaks:
  textWrapOptions:
    columns: 92
replacements:
  - substitution: |-
      s/\$\$
        (.*?)
        \$\$/\\[$1\\]/sgx
  - substitution: |-
      s/\$
        (.*?)
        \$/\\($1\\)/sgx
