name: Render RMarkdown and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Render site
        run: |
          rmarkdown::render_site(encoding = 'UTF-8')

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site/"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
